[build]
  publish = "publish"
  functions = "functions-zip"

[[redirects]]
  from = "/product-page/faria-s-coffee"
  to = "/faria-coffeee"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr?slug=:splat"
  status = 200

[[headers]]
  for = "/storefront.*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/storefront.*.*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/storefront.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/storefront.css"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/checkout.*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/checkout.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/chunk.*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/chunk.*.*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=300, s-maxage=60, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=86400, s-maxage=600"

[[redirects]]
from = "/product-page/café-filippeto-torrado-em-grãos-500g"
to = "/filippeto-em-graos-pacote-500g"
status = 301
force = true

[[redirects]]
from = "/product-page/a-coffee-torrado-em-grãos-1"
to = "/a-coffee"
status = 301
force = true

[[redirects]]
from = "/product-page/faria-s-coffee-torrado-em-grãos-500g"
to = "/farias-em-graos-pacote-500g"
status = 301
force = true

[[redirects]]
from = "/_frog"
to = "/combos-cia-coffee"
status = 301
force = true

[[redirects]]
from = "/product-page/a-coffee"
to = "/a-coffee"
status = 301
force = true

[[redirects]]
from = "/product-page/café-filippeto-torrado-em-pó-500g"
to = "/filippeto-moido-pacote-500g"
status = 301
force = true

[[redirects]]
from = "/bolt-performance?src=72&evid="
to = "/combos-cia-coffee"
status = 301
force = true

[[redirects]]
from = "/loja"
to = "/combos-cia-coffee"
status = 301
force = true

[[redirects]]
from = "/sobre"
to = "/pages/sobre-nos"
status = 301
force = true

[[redirects]]
from = "/lead-collection"
to = "/combos-cia-coffee"
status = 301
force = true

[[redirects]]
from = "/cadastroefetuado"
to = "/pages/sobre-nos"
status = 301
force = true

[[redirects]]
from = "/assinatura"
to = "/pages/sobre-nos"
status = 301
force = true

[[redirects]]
from = "/política-da-loja"
to = "/pages/privacidade"
status = 301
force = true

[[redirects]]
from = "/cart-page"
to = "/app/#/cart"
status = 301
force = true

